# Generated by Django 5.0.1 on 2024-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_artist_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=130),
        ),
        migrations.AddField(
            model_name="review",
            name="slug",
            field=models.SlugField(blank=True, max_length=130),
        ),
    ]
