# Generated by Django 5.0.1 on 2024-08-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_news_slug_review_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="image",
            new_name="image_1",
        ),
        migrations.AddField(
            model_name="news",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image_4",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image_6",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
