# Generated by Django 5.0.1 on 2024-08-17 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_news_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
