# Generated by Django 5.0.1 on 2024-08-20 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_news_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Обзор картин",
                "verbose_name_plural": "Обзоры картин",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="paintings/"),
        ),
    ]
